### PR TITLE
Ability to use custom ScheduledExecutorService when building a TraceGrpcApiService

### PR DESCRIPTION
**Pull request by fabito**
I'm building a Dropwizard/Jersey bundle and I need to provide my own ScheduledExecutorService.

### CODE REVIEW

**Comment by kevinmdavis** [comment]
You may be interested in our instrumentation repository. You should be able to use the jax-rs and servlet instrumentation with Dropwizard/Jersey.

https://github.com/GoogleCloudPlatform/cloud-trace-java-instrumentation

**Comment by fabito** [comment]
Thanks, didn't know about the instrumentation repo!
Are you planning to publish/release to maven central anytime soon ?

**Comment by kevinmdavis** [comment]
Yes, I'll be doing that soon (hopefully in the next day or two).

**Comment by fabito** [comment]
Just saw 0.2.3 was released. How long until its published on maven central ? Any idea?

**Comment by kevinmdavis** [comment]
It should be syncing from Sonatype to the Central repo now.

**Pull request merged**
